version: '2'

services:
  node:
    image: node:8.10
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ${app_path}:/app
    command:  bash -c "npm install && npm start"
    restart: unless-stopped