version: '2'
volumes:
  hastebin-data:
    driver: local

services:
  hastebin:
    image: rlister/hastebin:latest
    labels:
      io.rancher.container.hostname_override: container_name
    environment:
      STORAGE_TYPE: redis
      STORAGE_HOST: redis
    restart: unless-stopped
  redis:
    image: redis:4.0.9
    volumes:
      - hastebin-data:/data
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes