version: '2'
volumes:
  webserver-data:
    driver: local

services:
  webserver-php:
    image: richarvey/nginx-php-fpm:1.4.1
    volumes:
      - webserver-data:/var/www/html
    restart: unless-stopped
    environment:
      - GIT_EMAIL=git@cyberdos.de
      - GIT_NAME=AutoPuller
      - GIT_USE_SSH=1
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_REPO=${GIT_REPO}
      - SSH_KEY=${SSH_KEY}