version: '2'

services:
  nginx:
    image: nginx:1.13.10
    volumes:
      - ${site_config}:/etc/nginx/conf.d/default.conf:ro
      - ${web_path}:/www
    links:
        - php
    restart: unless-stopped
  php:
    image: php:7.2.3-fpm
    volumes:
      - ${web_path}:/www
    restart: unless-stopped