version: '2'
volumes:
  webserver-data:
    driver: local

services:
  nginx:
    image: nginx:1.13.10
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - webserver-data:/www
    links:
        - php
    restart: unless-stopped
  php:
    image: php:7.2.3-fpm
    volumes:
      - webserver-data:/www
    restart: unless-stopped