.catalog:
  name: Webserver PHP
  version: v7.2.3
  uuid: webserver-php-0

nginx:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
php:
  scale: 1
  retain_ip: true